### ISSUE TITLE
FluxBitcoin Widget no aparece en Smartwatch2 de Sony

### ISSUE THREAD

**Issue by Yhoni** [Giszmo/fluxbitcoin-monitor#1]
Hola, yo tengo un Huawei P9 Lite con Emui y cuando instalo el programa FluxBitcoin Widget aparece en la lista de aplicaciones instaladas en el teléfono pero no aparece en mi Smartwatch2 de Sony. 

Sería genial que se pudiera solucionar este problema.

Siento no poder ayudar más porque yo tengo conocimientos básicos de html y css pero no conozco nada de programación Android.

Enhorabuenas por la aplicación y gracias.

**Comment by Giszmo** [comment]
:) poco tarde que encuentro este issue. Mil disculpas. El proyecto nunca se volvio mucho de prioridad.
