### ISSUE TITLE
Is this repo the current one?

### ISSUE THREAD

**Issue by mvglasow** [Giszmo/fluxbitcoin-monitor#2]
F-Droid ([metadata](https://gitlab.com/fdroid/fdroiddata/-/blob/master/metadata/de.leowandersleb.bitcoinsw.yml)) has a BitBucket archive for the source code repo, which won’t be getting any more updates. Are you still developing this app? If so, where do you keep the current source code?

**Comment by Giszmo** [comment]
This app stopped working at some point and I couldn't even find the SDK or if there was an update back then. Sorry.
